---
# Use the following command to test globs locally:

# Add 'agent' label to any changes within 'guides' that references 'agent'
agent:
  - '(agent|alloy|collector)'

# Add 'alerting' label to any changes within 'guides' that references 'alert'
alerting:
  - '(alert|alerting|notification|rule|silence|receiver|route|route)'

# Add 'alertmanager' label to any changes within 'guides' that references 'alert'
alertmanager:
  - '(alertmanager|am|amtool)'

# Add 'dashboard' label to any changes within 'guides' that references 'dashboard'
dashboard:
  - '(dashboard|dash|graph|panel|row|stat|table|singlestat|gauge|graph|heatmap|timeseries)'

# Add 'grafana' label to any changes within 'guides' that references 'grafana'
grafana:
  - '(grafana|datasource)'

# Add 'helm' label to any changes within 'guides' that references 'helm'
helm:
  - ('helm|chart|values')

# Add 'incident' label to any changes within 'guides' that references 'helm'
incident:
  - '(incident)'

# Add 'k6' label to any changes within 'guides' that references 'k6'
k6:
  - '(k6|loadtest)'

# Add 'kubernetes' label to any changes within 'guides' that references 'kube' or 'k8s'
kubernetes:
  - '(kube|k8s|kubernetes|cdadvisor|cadvisor|kubeadm|kubectl|kubeproxy|kube-proxy|kube-scheduler|kube-scheduler|kube-controller|kube-controller|kube-apiserver|kube-apiserver|kubelet)'

# Add 'loki' label to any changes within 'guides' that references 'loki' or 'gel' or 'log'
loki:
  - '(loki|gel|log|logql|enterprise(-| )log)'

# Add 'mimir' label to any changes within 'guides' that references 'mimir' or 'gem' or 'metrics'
#  or 'prometheus' or 'promql'
mimir:
  - '(mimir|gem|metrics|prometheus|promql|enterprise(-| )metric)'

# Add 'oncall' label to any changes within 'guides' that references 'oncall'
oncall:
  - '(oncall|on-call)'

# Add 'openshift' label to any changes within 'guides' that references 'openshift'
openshift:
  - '(openshift|oc|oadm|oadmin|ocp|okd|openshift-origin)'

# Add 'otel' label to any changes within 'guides' that references 'otel' or 'instrument' or 'telemetry' or 'tracing'
otel:
  - '(otel|instrument|telemetry|trace|tracing|opentelemetry|jaeger|zipkin)'

# Add 'plugin' label to any changes within 'guides' that references 'openshift'
plugin:
  - '(plugin|extension|integration)'

# Add 'pyroscope' label to any changes within 'guides' that references 'pyroscope' or 'profil'
pyroscope:
  - '(pyroscope|profile|profiling|cpu|memory|heap|goroutine|goroutines|flamegraph|flame)'

# Add 'tempo' label to any changes within 'guides' that references 'tempo' or 'trac'
tempo:
  - '(tempo|trace|tracing|jaeger|zipkin|opentelemetry)'

# Add 'terraform' label to any changes within 'guides' that references 'terraform' or 'tf'
terraform:
  - '(terraform|tf|provider)'

# Add 'windows' label to any changes within 'guides' that references 'windows'
windows:
  - '(windows|win|wmi|perfmon|eventlog|event-log|eventviewer|event-viewer)'
