---
name: Pull Request Labeler

# yamllint disable-line rule:truthy
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          # automatically add labels to pull requests based on the files changed
          configuration-path: .github/pr-labeler.yml
